from __future__ import annotations

from typing import List


# Broad label space: COCO-ish + common products + starter engineering parts.
# Keep as plain labels; we will convert to CLIP prompts in processing.

def get_labels() -> List[str]:
    coco = [
        "person",
        "bicycle",
        "car",
        "motorcycle",
        "airplane",
        "bus",
        "train",
        "truck",
        "boat",
        "traffic light",
        "fire hydrant",
        "stop sign",
        "parking meter",
        "bench",
        "bird",
        "cat",
        "dog",
        "horse",
        "sheep",
        "cow",
        "elephant",
        "bear",
        "zebra",
        "giraffe",
        "backpack",
        "umbrella",
        "handbag",
        "tie",
        "suitcase",
        "frisbee",
        "skis",
        "snowboard",
        "sports ball",
        "kite",
        "baseball bat",
        "baseball glove",
        "skateboard",
        "surfboard",
        "tennis racket",
        "bottle",
        "wine glass",
        "cup",
        "fork",
        "knife",
        "spoon",
        "bowl",
        "banana",
        "apple",
        "sandwich",
        "orange",
        "broccoli",
        "carrot",
        "hot dog",
        "pizza",
        "donut",
        "cake",
        "chair",
        "couch",
        "potted plant",
        "bed",
        "dining table",
        "toilet",
        "tv",
        "laptop",
        "mouse",
        "remote",
        "keyboard",
        "cell phone",
        "microwave",
        "oven",
        "toaster",
        "sink",
        "refrigerator",
        "book",
        "clock",
        "vase",
        "scissors",
        "teddy bear",
        "hair drier",
        "toothbrush",
    ]

    products = [
        "smartphone",
        "mobile phone holder",
        "phone mount",
        "tripod",
        "camera",
        "action camera",
        "webcam",
        "headphones",
        "earbuds",
        "charger",
        "power bank",
        "usb cable",
        "keyboard",
        "computer mouse",
        "monitor",
        "tablet",
        "notebook",
        "notebook page",
        "document",
        "printed document",
        "form",
        "engineering drawing",
        "blueprint",
        "barcode",
        "qr code",
        "label",
        "packaging",
        "box",
        "bottle cap",
        "water purifier",
        "filter cartridge",
        "clamp",
        "bracket",
        "hook",
        "hinge",
        "handle",
        "knob",
        "switch",
        "remote control",
        "pen",
        "pencil",
        "marker",
        "tool",
        "wrench",
        "screwdriver",
        "pliers",
        "hammer",
        "drill",
        "measuring tape",
        "caliper",
    ]

    engineering_parts = [
        "bolt",
        "screw",
        "nut",
        "washer",
        "stud",
        "rivet",
        "bearing",
        "ball bearing",
        "roller bearing",
        "gear",
        "spur gear",
        "helical gear",
        "rack and pinion",
        "shaft",
        "axle",
        "coupling",
        "pulley",
        "belt",
        "chain",
        "sprocket",
        "spring",
        "compression spring",
        "torsion spring",
        "o-ring",
        "gasket",
        "seal",
        "valve",
        "ball valve",
        "gate valve",
        "check valve",
        "pipe",
        "tube",
        "hose",
        "fitting",
        "elbow fitting",
        "tee fitting",
        "flange",
        "nozzle",
        "manifold",
        "pump",
        "motor",
        "servo motor",
        "stepper motor",
        "fan",
        "heat sink",
        "enclosure",
        "housing",
        "cover plate",
        "mounting plate",
        "base plate",
        "frame",
        "rail",
        "linear rail",
        "slider",
        "bushing",
        "spacer",
        "standoff",
        "connector",
        "terminal block",
        "pcb",
        "circuit board",
        "sensor",
    ]

    # De-dup while preserving order
    seen = set()
    out: List[str] = []
    for lst in (coco, products, engineering_parts):
        for x in lst:
            k = x.strip().lower()
            if not k or k in seen:
                continue
            seen.add(k)
            out.append(x)
    return out
